name: Deploy Boty QA

on:
  push:
    branches:
      - develop  # Trigger on develop branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: boty-qa

    steps:
      # Checkout Repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repo

      # Build Docker Image locally
      - name: Build Docker image
        run: |
          cd repo
          docker build -t fernuni-bot:latest .

      # Deploy with Docker Compose
      - name: Deploy Bot
        run: |
          cd repo
          docker compose up -d
